// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmfhygfkzgtsyzbauzeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtZmh5Z2Zremd0c3l6YmF1emVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0OTg5NjQsImV4cCI6MjA3NTA3NDk2NH0.eJV6hEkPe2K8UO_3I52Tx9PP36ev1YhdgiIisEZDdok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});